# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dc8f7872c4479bbf464ac0e092ba80bc"
name = "vstats"
application_url = "https://soviet-templates-conversations-arrangements.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "vstats.myshopify.com"

[auth]
redirect_urls = [
  "https://soviet-templates-conversations-arrangements.trycloudflare.com/auth/callback",
  "https://soviet-templates-conversations-arrangements.trycloudflare.com/auth/shopify/callback",
  "https://soviet-templates-conversations-arrangements.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
